export * from './Landing'
export * from './Buy'
export * from './Login'
export * from './Dashboard'
export * from './Activate'
export * from './Public'
export * from './RecoverPassword'
export * from './UpdatePassword'
export * from './Conditions'
export * from './SOSContact'
export * from './ProfilesView'
export * from './Settings'
export * from './Emergency'

